#!/bin/sh

set -e

usage() {
	echo "Usage: pvr2adu [options] <install-agent|export> [arguments]"
	echo "Convert pvr checkout and images into ADU format"
	echo "options:"
	echo "       -h this help"
	echo "       -v verbose"
}

usage_install_agent() {
	echo "Usage: pvr2adu [options] install-agent <connection-string> <manufacturer> <model>"
	echo "Install ADU agent in the current pvr checkout that will connect to ADU with the provided configuration"
}

usage_export() {
	echo "Usage: pvr2adu [options] export <provider> <name> <version> <manufacturer> <model> <part> <output>"
	echo "Export the current pvr checkout into ADU compatible format"
}

parse_args() {
	while [ $# -gt 0 ]; do
		key="$1"
		case "$key" in
			-h)
				usage
				exit 0
				;;
			-v)
				verbose="true"
				;;
			*)

				break
		esac
		shift
	done

	case "$1" in
		install-agent)
			cmd='install-agent'
			connectionstring="$2"
			manufacturer="$3"
			model="$4"
			;;
		export)
			cmd='export'
			provider="$2"
			name="$3"
			version="$4"
			manufacturer="$5"
			model="$6"
			part="$7"
			output="$8"
			;;
		*)
			usage; exit 1
			;;
	esac
}

check_args_install_agent() {
	if [ -z "$connectionstring" ]; then usage_install_agent; exit 1; fi
	if [ -z "$manufacturer" ]; then usage_install_agent; exit 1; fi
	if [ -z "$model" ]; then usage_install_agent; exit 1; fi
}

check_args_export() {
	if [ -z "$provider" ]; then usage_export; exit 1; fi
	if [ -z "$name" ]; then usage_export; exit 1; fi
	if [ -z "$version" ]; then usage_export; exit 1; fi
	if [ -z "$manufacturer" ]; then usage_export; exit 1; fi
	if [ -z "$model" ]; then usage_export; exit 1; fi
	if [ -z "$part" ]; then usage_export; exit 1; fi
	if [ -z "$output" ]; then usage_export; exit 1; fi

	exportname="$version.tgz"
	manifestname="$version.importmanifest.json"
}

install_agent() {
	if [ ! -e _hostconfig/pvr/docker.json ]; then
		echo "no _hostconfig found in pvr checkout"
		exit 1
	else
		grep -q amd64 _hostconfig/pvr/docker.json && target="amd64-pvcontainer-0-8-0"
		grep -q arm _hostconfig/pvr/docker.json && target="arm32v7-pvcontainer-0-8-0"
		grep -q arm64 _hostconfig/pvr/docker.json && target="arm64v8-pvcontainer-0-8-0"
	fi

	if [ -z "$target" ]; then
		echo "unknown target"
		exit 1
	fi
	if [ -n "$verbose" ]; then echo "installing adu agent for $target"; fi

	pvr app add --from registry.gitlab.com/pantacor/pv-platforms/adu-agent:$target azure-client
} 

install_config() {
	mkdir -p _config/azure-client/etc/adu
	json=`jq -n \
		--arg cs "$connectionstring" \
		--arg ma "$manufacturer" \
		--arg mo "$model" \
		'{
			schemaVersion: "1.0",
			aduShellTrustedUsers: [
				"adu",
				"do"
			],
			manufacturer: $ma,
			model: $mo,
			agents: [
				{
					name: "pvcontrol",
					runas: "adu",
					connectionSource: {
						connectionType: "string",
						connectionData: $cs
					},
					manufacturer: $ma,
					model: $mo
				}
			]
		}'`
	echo $json > _config/azure-client/etc/adu/du-config.json
}

create_tarball() {
	mkdir -p "$output"
	pvr export -p "$part" "$output/$exportname"
	ls "$output/$exportname"
}

create_manifest() {
	$(dirname $0)/AduCmdlets/create-adu-import-manifest.sh \
		-p "$provider" \
		-n "$name" \
		-v "$version" \
		-h "pantacor/pvcontrol:1" \
		-c "deviceManufacturer:$manufacturer" \
		-c "deviceModel:$model" \
		-r "installedCriteria:$version" \
		"$output/$exportname"  > "$output/$manifestname"
	ls "$output/$manifestname"
}

exec_cmd() {
	case "$cmd" in
		install-agent)
			check_args_install_agent
			install_agent
			install_config
			;;
		export)
			check_args_export
			create_tarball
			create_manifest
			;;
		*)
			echo "ERROR: unknown operation"; usage; exit 1
			;;
	esac
}

parse_args "$@"
exec_cmd
